---
- name: Configure MOTD Banner
  hosts: routers
  gather_facts: false
  connection: network_cli
  
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: admin
    ansible_password: cisco
    ansible_connect_timeout: 20
    
  tasks:
    - name: Set MOTD
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ motd_message }}"
        state: present